INSERT INTO va_directory (company_name, website, hires_filipinos, niche, notes) VALUES
('PropVA', 'https://propva.co.uk', 1, 'admin', 'UK-based agency specialising in Filipino VAs for UK property / e-commerce / marketing.'),
('Philippines Recruitment UK', 'https://philippinesrecruitment.co.uk/', 1, 'other', 'UK-based recruitment agency that specialises in connecting Filipino freelancers (including VAs) with UK SMEs. They emphasise cost-effective, English-proficient Filipino professionals who can work UK hours.'),
('Staff Avenue', 'https://staffavenue.co.uk/hire-virtual-staff-in-philippines/', 1, 'admin', 'UK & Europe oriented staffing agency which connects UK businesses with virtual staff in the Philippines — emphasising admin, tech, and customer service.'),
('Manpower Genius', 'https://manpowergenius.com/guide-for-uk-businesses/unlocking-efficiency-and-talent-outsourcing-your-office-staff-to-the-philippines-with-manpower-genius/', 1, 'admin', 'British-owned headhunter/remote staffing agency that specialises in helping UK businesses hire Filipino virtual assistants and remote staff.'),
('DigiWorks', 'https://www.teamdigiworks.com/virtual-assistant-from-the-philippines', 1, 'admin', 'Platform that allows small/medium UK (and other) businesses to hire Filipino remote staff including virtual assistants, with their system handling matching/vetting.'),
('SOS VA Services / Smart Outsourcing Solution', 'https://smartoutsourcingsolution.com/virtual-assistant-services-philippines/', 1, 'admin', 'Global outsourcing firm that offers Filipino virtual assistants covering admin, marketing, customer support; offers part-time and project-based models (suitable for UK hours).'),
('Easy Outsourcing', 'https://easy-outsourcing.com', 1, 'other', 'Boutique UK/Philippines outsourcing agency offering Filipino VAs for UK & Europe.'),
('Officium', 'https://officium.ph', 1, 'other', 'A UK company mentioned in job-threads that provides managed Filipino VA services to UK clients.'),
('Digital SPS', 'https://digitalsps.co.uk/hire-Philippines-virtual-assistant.php', 1, 'admin', 'UK digital agency advertising Filipino virtual assistants for remote tasks, with flexible global hiring model.'),
('CreaThink Solutions', 'https://creathink-solutions.com', 1, 'customer-support', 'UK-Philippines outsourcing advisor/firm that supports UK businesses to hire Filipino VAs.'),
('KDCI Outsourcing', 'https://kdci.co', 1, 'admin', 'Outsourcing firm servicing global markets including UK, offering Filipino virtual assistants'),
('Virtual Coworker', 'https://virtualcoworker.com.au/', 1, 'admin', 'Established Aussie agency (since 2011) placing vetted Filipino VAs across admin, marketing, tech, and real estate.'),
('Remote Staff (Australia)', 'https://www.remotestaff.com.au/', 1, 'customer-support', 'Australia-founded remote staffing firm hiring Filipino VAs for AU & NZ clients, with recruitment and management support.'),
('Flat Planet', 'https://flatplanet.com.au/hire-filipino-virtual-assistant/', 1, 'admin', 'Australian agency linking Aussie businesses with Filipino VAs for admin, support, and marketing roles. 5. Virtual Assistant Team - https:/ /www.virtualassistantteam.com.au/ Provides highly skilled VAs for daily admin support and specialised projects.'),
('Outsource Workers', 'https://outsourceworkers.com.au/', 1, 'admin', 'Australian company specialising in trained Filipino real estate virtual assistants.'),
('Virtual Elves', 'https://virtualelves.com.au/', 1, 'other', 'Australian VA agency hiring Filipino VAs and matching them quickly with Aussie businesses.'),
('StaffingSolutions.io (SSIO)', 'https://staffingsolutions.io/', 1, 'other', 'Helps Australian companies hire Filipino VAs with scalable, cost-effective staffing options.'),
('WorkMate Pro', 'https://www.workmatepro.com/', 1, 'other', 'Platform connecting Filipino VAs with international clients, focused on productivity and role matching.'),
('Global Teams', 'https://globalteams.com.au/career-philippines/', 1, 'other', 'Australian remote staffing firm hiring Philippines-based VAs through local career pages.'),
('ArmA Sourcing', 'https://armasourcing.com/', 1, 'other', 'Provides Filipino VA staffing solutions tailored for Australian businesses.'),
('Outshore', 'https://outshore.com.au/', 1, 'admin', 'Australian outsourcing firm placing Filipino remote staff for admin, digital, and dev roles.'),
('Beepo', 'https://www.beepo.com.au/', 1, 'admin', 'Australian outsourcing platform offering Filipino VAs for admin and support roles.'),
('ProSource', 'https://prosource.com.au/', 1, 'admin', 'Outsourcing agency recruiting Filipino VA contractors for admin, e-commerce, and marketing.'),
('WorkspaceCo Outsourcing', 'https://workspacecooutsourcing.com/', 1, 'admin', 'Australian firm hiring university-educated Filipino VAs for admin, social media, and e-commerce.'),
('Platinum Outsourcing', 'https://platinumoutsourcing.com.au/', 1, 'tech', 'Outsourcing provider offering Filipino staff for VA, customer support, design, and tech roles.'),
('AgentSync', 'https://agentsync.com.au/', 1, 'other', 'Offers Essential and Elite Filipino VAs for Australian clients, full-time or part-time. Every successful VA once stood exactly where you are now—uncertain, learning, and taking that first step. You don’t have to be ready. You just have to start. 🤍 CTTO: The VA GUIDES 💯'),
('Smart Outsourcing Solution (SOS)', 'https://smartoutsourcingsolution.com/', 1, 'other', 'Premium EOR-wrapped model for SaaS scale-ups with a flat monthly fee covering compliance, payroll, and HR.'),
('CrewBloom', 'https://www.crewbloom.com/', 1, 'other', 'High-growth outsourcing agency connecting top 2% of Filipino remote talent with global businesses.'),
('SuperStaff', 'https://superstaff.com/', 1, 'admin', 'Enterprise-grade BPO providing specialized virtual assistants for admin, e-commerce, and customer service.'),
('Booth & Partners', 'https://boothandpartners.com/', 1, 'other', 'Offers tailored offshore staffing solutions with a focus on sustainability and high-quality Filipino talent.'),
('Stellar Staff', 'https://stellarstaff.com/', 1, 'admin', 'Emerging agency providing dedicated Filipino VAs for real estate, marketing, and administrative roles.'),
('Outsourcey', 'https://outsourcey.com/', 1, 'admin', 'Australian-owned agency specializing in high-quality Filipino virtual assistants for SMEs.'),
('Access Offshoring', 'https://accessoffshoring.com.au/', 1, 'other', 'Provides tailored offshore staffing solutions for businesses worldwide.'),
('Cool Pixels', 'https://www.coolpixels.com.au/', 1, 'creative', 'Specializes in virtual assistants for creative/digital marketing tasks.'),
('24x7 Direct', 'https://www.24x7direct.com.au/', 1, 'admin', '24/7 virtual assistants for customer support/admin tasks.'),
('Virtual Staff 365', 'https://www.virtualstaff365.com.au/', 1, 'admin', 'Connects businesses with skilled virtual assistants.'),
('Remote Staff Philippines', 'https://www.remotestaff.ph/', 1, 'tech', 'A decade-old offshore staffing provider offering virtual assistance, web development, and digital marketing services with flexible pricing.'),
('Clear Admin People', 'https://www.adminpeople.com.au/', 1, 'admin', 'Professional virtual assistants for admin/operational support.'),
('Virtual Champions', 'https://virtualchampions.ph/', 1, 'other', 'VAs for entrepreneurs/small businesses.'),
('OnlineHelpers', 'https://onlinehelpers.info/', 1, 'other', 'Australian-owned offshore virtual assistance for SMEs.'),
('My Cloud Assistant', 'https://www.mycloudassistant.com.au/', 1, 'other', 'Tailored VA services for professionals/SMBs.'),
('OVA Virtual Assistant', 'https://ovavirtual.com/', 1, 'other', 'Women-led VA company based in the Philippines.'),
('Bottleneck Distant Assistants', 'https://bottleneck.online/', 1, 'other', 'Specialized VA roles with trained staff.'),
('Global Hola', 'https://www.globalhola.com', 1, 'other', 'Fun, inclusive virtual culture for Filipino VAs.'),
('Olivia Pros', 'https://www.oliviapros.com/careers', 1, 'other', 'WFH opportunities for Filipino VAs.'),
('My Virtudesk', 'https://myvirtudesk.com/', 1, 'admin', 'Industry-specific VAs (real estate, marketing).'),
('Fast Track FBA', 'https://fasttrackfba.com/', 1, 'other', 'Amazon FBA-focused VA services.'),
('VirtualHub PH', 'https://virtualhub.ph/', 1, 'other', 'VA services for Philippine-based businesses.'),
('Pineapple Staffing', 'https://pineapplestaffing.com/', 1, 'other', 'Virtual staffing solutions including VAs.'),
('Coconut VA', 'https://coconutva.com/', 1, 'customer-support', 'General business task support.'),
('VirtualStaff', 'https://www.virtualstaff.ph/', 1, 'other', 'Pre-vetted VA hiring platform.'),
('OnlineJobs', 'https://www.onlinejobs.ph/', 1, 'other', 'Direct VA hiring platform.'),
('MyOutDesk', 'https://www.myoutdesk.com/', 1, 'admin', 'Real estate-focused VAs.'),
('EVirtualAssistants', 'https://www.evirtualassistants.com/', 1, 'other', 'Direct client-VA communication platform.'),
('TaskBullet', 'https://www.taskbullet.com/', 1, 'other', 'Hourly VA services with "bucket system".'),
('USource', 'https://usource.me/services/virtual-assistants/', 1, 'creative', 'Full-time VAs for digital marketing/support.'),
('Hello Rache', 'https://hellorache.com/', 1, 'other', 'Healthcare VAs with medical training.'),
('MultiplyMii', 'https://www.multiplymii.com/', 1, 'other', 'Career-focused VA matching.'),
('Support Shepherd', 'https://www.somewhere.com/', 1, 'admin', 'Customer service/admin VAs.'),
('Pepper Virtual Assistants', 'https://peppervirtualassistant.com/', 1, 'other', 'Reliable VA services across industries.'),
('24/7 Virtual Assistant', 'https://20four7va.com/', 1, 'customer-support', 'Round-the-clock VA support.'),
('GetFriday', 'https://www.getfriday.com/', 1, 'other', 'Personalized business/personal assistance.'),
('My Freight Staff', 'https://myfreightstaff.ph/', 1, 'other', 'Freight/logistics-specific VAs.'),
('HighCall', 'https://highcallva.com/', 1, 'other', 'Medical transcription/billing VAs.'),
('Athena Executive Assistants', 'https://jobs.athenago.com', 1, 'creative', 'Robust training programs and social media focus; 100% remote work for Filipinos.'),
('The VA Hub PH', 'https://thevahub.org', 1, 'admin', 'Specialized training for real estate, marketing, and sales VAs (since 2016).'),
('HireTalent.ph', 'https://hiretalent.ph', 1, 'other', 'Rigorous vetting with "job points" and sample tasks to showcase skills.'),
('Magic Virtual Assistant Services', 'https://getmagic.pinpointhq.com', 1, 'other', 'Connects VAs to global startups (earnings start at $5/hour).'),
('Outsource Accelerator', 'https://outsourceaccelerator.com', 1, 'other', 'Global marketplace listing 3,000+ BPOs for staff leasing and recruitment.'),
('VA Staffer', 'https://vastaffer.com', 1, 'admin', 'Vetted virtual executive assistants with technical expertise.'),
('LinkedVA', 'https://linkedva.com/careers/', 1, 'other', 'Offers paid training and a "best team in the universe" culture for Filipino VAs.'),
('GoVirtuals', 'https://govirtuals.com', 1, 'creative', 'Australian-Filipino VA company specializing in digital marketing and brand strategy.'),
('Virtual Done Well', 'https://virtualdonewell.com', 1, 'customer-support', 'Davao City-based VA provider for email management and customer service.'),
('Remote Workmate', 'https://remoteworkmate.com', 1, 'other', 'Australian platform offering free trials and employee swap programs for SMEs.'),
('GoHireNow', 'https://gohirenow.com', 1, 'customer-support', 'US marketplace connecting employers with Filipino VAs, emphasizing fair pay and seamless hiring for roles like content creation and IT support.'),
('iWork.ph', 'https://iwork.ph', 1, 'admin', 'A Filipino-based platform widely used by Japanese employers to hire VAs for tasks like administrative support, data entry, and customer service. Offers transparent pricing and secure transaction management 12.'),
('Quantum Virtual Assistants', 'https://quantumvirtualassistant.com', 1, 'admin', 'A global platform connecting European businesses with Filipino VAs for specialized tasks like digital marketing, content creation, and administrative support. Emphasizes rigorous vetting and cultural alignment with Western clients 6.'),
('Remote Raven', 'https://hireremoteraven.com', 1, 'tech', 'A European-focused agency offering pre-vetted Filipino VAs for roles like social media management, customer support, and technical assistance. Known for its seamless onboarding and AI-driven task automation 10.'),
('Scotiabank Canada', 'https://scotiabank.com', 1, 'admin', 'Offers remote administrative and customer service roles, with pathways for Filipino VAs through LMIA-supported positions 14.'),
('KPMG Canada', 'https://kpmg.ca', 1, 'finance', 'Auditing firm hiring remote VAs for finance and project coordination, with sponsorship options under Canada’s TFWP 14.'),
('Elastic Path', 'https://elasticpath.com', 1, 'tech', 'Vancouver-based tech company recruiting bilingual (English/French) VAs for sales support and digital operations 14.'),
('Hilton Hotels Australia', 'https://hilton.com.au', 1, 'customer-support', 'Hospitality giant hiring remote customer service VAs for reservations and client management roles 9.'),
('Ramsay Health Care', 'https://ramsayhealth.com', 1, 'admin', 'Healthcare provider seeking remote administrative VAs for patient coordination and data entry 9.'),
('REassist', 'reassist.com.au', 1, 'admin', 'Focuses on real estate VAs, helping Australian property businesses streamline rent roll management and client communication. Partners with Filipino VAs trained in property software like CoreLogic 4.'),
('PMVA (Property Management Virtual Assistant)', 'pmva.com.au', 1, 'admin', 'Brisbane-based firm expanding into the Philippines, offering VAs skilled in real estate workflows, lease administration, and tenant coordination. Provides bilingual support for Australian property managers 4.'),
('Capital EA', 'capitalea.com.au', 1, 'admin', 'A "boutique" VA agency targeting executives and educational institutions. Sources Filipino VAs with expertise in high-level admin tasks, report preparation, and event coordination 4.'),
('MS Virtual Assistant', 'msvirtualassistant.com.au', 1, 'admin', 'Fully Australian-based but hires Filipino VAs for time zone alignment. Specializes in outbound calling, website management, and administrative tasks for local businesses 4.'),
('Vaxtra', 'vaxtra.com', 1, 'customer-support', 'Provides end-to-end VA solutions, including seat leasing in Southeast Asia. Focuses on customer service and HR support, leveraging Filipino talent for cost savings (~15–20 AUD/hour) 4.'),
('Galilee Business Support Services (GBSS)', 'gbss.com.au', 1, 'admin', 'Sydney-based BPO connecting Australian firms with Filipino VAs for accounting, real estate, and HR roles. Emphasizes cultural alignment and cost efficiency (~12–18 AUD/hour) 4.'),
('The Property VA', 'thepropertyva.co.uk', 1, 'admin', 'A UK-based agency specializing in connecting property investors with Filipino VAs for tasks like tenant communication, CRM management, and social media. Focuses on bridging cultural gaps and providing cost-effective solutions for UK real estate businesses 9.'),
('Virtalent UK', 'virtalent.com', 1, 'creative', 'UK-focused VA platform hiring experienced professionals (including Filipinos residing in the UK) for roles like diary management, marketing support, and project coordination. Offers flexible hours and emphasizes rigorous vetting 11.'),
('Outsourcing Angel', 'https://outsourcingangel.com', 1, 'customer-support', 'Ethically sources top 10% of Filipino VAs, emphasizing sustainability and cultural alignment. Offers a lifetime replacement guarantee and holistic support for SMEs 12.');
