DELETE FROM va_directory;
INSERT INTO va_directory (company_name, niche, is_dayshift, is_verified, is_remote, is_marketplace, website) VALUES
('Upwork', 'global-va', 0, 1, 1, 1, 'https://www.upwork.com'),
('FJ Accountants Limited', 'job-boards', 0, 1, 1, 0, 'https://fjaccountants.com'),
('Filipino Virtual Assistants (FVA)', 'job-boards', 0, 1, 1, 0, 'https://fvacademy.com'),
('Intogreat Solutions', 'job-boards', 0, 1, 1, 0, 'https://intogreat.com.au'),
('Shepherd', 'job-boards', 0, 1, 1, 0, 'https://www.supportshepherd.com'),
('The Freelance Movement', 'job-boards', 0, 1, 1, 0, 'https://www.thefreelancemovement.com'),
('VA Bootcamp PH', 'job-boards', 0, 1, 1, 0, 'https://vabootcamp.ph'),
('WHR Global Consulting', 'job-boards', 0, 1, 1, 0, 'https://whrglobal.com'),
('Affordable Staff', 'australian-dayshift', 1, 1, 1, 0, 'https://affordablestaff.com.au'),
('Diversify', 'australian-dayshift', 1, 1, 1, 0, 'https://diversifyoss.com'),
('EzyVA', 'australian-dayshift', 1, 1, 1, 0, 'https://ezyva.com'),
('Hudson Remote Talent', 'australian-dayshift', 1, 1, 1, 0, 'https://au.hudson.com/hudson-remote-talent'),
('Shore360', 'australian-dayshift', 1, 1, 1, 0, 'https://shore360.com'),
('Vyla', 'australian-dayshift', 1, 1, 1, 0, 'https://vyla.com.au'),
('Yoonet', 'australian-dayshift', 1, 1, 1, 0, 'https://www.yoonet.io'),
('20Four7VA', 'global-va', 0, 1, 1, 0, 'https://20four7va.com'),
('24/7 Virtual Assistant', 'global-va', 0, 1, 1, 0, 'https://20four7va.com/'),
('24x7 Direct', 'global-va', 0, 1, 1, 0, 'https://www.24x7direct.com.au/'),
('AUMTREND PH', 'global-va', 0, 1, 1, 0, 'https://aumtrend.com'),
('AUMTREND PH INC', 'global-va', 0, 1, 1, 0, 'https://aumtrend.com'),
('Access Offshoring', 'global-va', 0, 1, 1, 0, 'https://accessoffshoring.com.au/'),
('AgentSync', 'global-va', 0, 1, 1, 0, 'https://agentsync.com.au/'),
('ArmA Sourcing', 'global-va', 0, 1, 1, 0, 'https://armasourcing.com/'),
('Athena Executive Assistants', 'global-va', 0, 1, 1, 0, 'https://jobs.athenago.com'),
('Beepo', 'global-va', 0, 1, 1, 0, 'https://www.beepo.com.au/'),
('Belay Solutions', 'global-va', 0, 1, 1, 0, 'https://belaysolutions.com'),
('Big Outsource', 'global-va', 0, 1, 1, 0, 'https://bigoutsource.com'),
('Boldly', 'global-va', 0, 1, 1, 0, 'https://boldly.com'),
('Booth & Partners', 'global-va', 0, 1, 1, 0, 'https://boothandpartners.com/'),
('Bottleneck Distant Assistants', 'global-va', 0, 1, 1, 0, 'https://bottleneck.online/'),
('Capital EA', 'global-va', 0, 1, 1, 0, 'capitalea.com.au'),
('Clear Admin People', 'global-va', 0, 1, 1, 0, 'https://www.adminpeople.com.au/'),
('ClearDesk', 'global-va', 0, 1, 1, 0, 'https://cleardesk.com'),
('Cloudstaff', 'global-va', 0, 1, 1, 0, 'https://www.cloudstaff.com'),
('Coconut VA', 'global-va', 0, 1, 1, 0, 'https://coconutva.com/'),
('Connext Global Solutions', 'global-va', 0, 1, 1, 0, 'https://connextglobal.com'),
('Cool Pixels', 'global-va', 0, 1, 1, 0, 'https://www.coolpixels.com.au/'),
('CreaThink Solutions', 'global-va', 0, 1, 1, 0, 'https://creathink-solutions.com'),
('CrewBloom', 'global-va', 0, 1, 1, 0, 'https://www.crewbloom.com/'),
('DigiWorks', 'global-va', 0, 1, 1, 0, 'https://www.teamdigiworks.com/virtual-assistant-from-the-philippines'),
('Digital SPS', 'global-va', 0, 1, 1, 0, 'https://digitalsps.co.uk/hire-Philippines-virtual-assistant.php'),
('EVirtualAssistants', 'global-va', 0, 1, 1, 0, 'https://www.evirtualassistants.com/'),
('Easy Outsourcing', 'global-va', 0, 1, 1, 0, 'https://easy-outsourcing.com'),
('Elastic Path', 'global-va', 0, 1, 1, 0, 'https://elasticpath.com'),
('Fast Track FBA', 'global-va', 0, 1, 1, 0, 'https://fasttrackfba.com/'),
('Flat Planet', 'global-va', 0, 1, 1, 0, 'https://flatplanet.com.au/hire-filipino-virtual-assistant/'),
('Galilee Business Support Services (GBSS)', 'global-va', 0, 1, 1, 0, 'gbss.com.au'),
('GetFriday', 'global-va', 0, 1, 1, 0, 'https://www.getfriday.com/'),
('Global Hola', 'global-va', 0, 1, 1, 0, 'https://www.globalhola.com'),
('Global Teams', 'global-va', 0, 1, 1, 0, 'https://globalteams.com.au/career-philippines/'),
('Go2', 'global-va', 0, 1, 1, 0, 'https://go2.io'),
('GoHireNow', 'global-va', 0, 1, 1, 0, 'https://gohirenow.com'),
('GoVirtuals', 'global-va', 0, 1, 1, 0, 'https://govirtuals.com'),
('Growth Assistant', 'global-va', 0, 1, 1, 0, 'https://growthassistant.com'),
('Hammerhead Virtual Assistants', 'global-va', 0, 1, 1, 0, 'https://hammerheadva.com'),
('Hello Rache', 'global-va', 0, 1, 1, 0, 'https://hellorache.com/'),
('HighCall', 'global-va', 0, 1, 1, 0, 'https://highcallva.com/'),
('Hilton Hotels Australia', 'global-va', 0, 1, 1, 0, 'https://hilton.com.au'),
('HireTalent.ph', 'global-va', 0, 1, 1, 0, 'https://hiretalent.ph'),
('Hit Rate Solutions', 'global-va', 0, 1, 1, 0, 'https://hitratesolutions.com'),
('KDCI Outsourcing', 'global-va', 0, 1, 1, 0, 'https://kdci.co'),
('KPMG Canada', 'global-va', 0, 1, 1, 0, 'https://kpmg.ca'),
('Kaya Services', 'global-va', 0, 1, 1, 0, 'https://kayaservices.com'),
('Kinetic Innovative Staffing', 'global-va', 0, 1, 1, 0, 'https://www.kinetic.com.ph'),
('LinkedVA', 'global-va', 0, 1, 1, 0, 'https://linkedva.com/careers/'),
('MCVO Talent Outsourcing', 'global-va', 0, 1, 1, 0, 'https://www.mcvotalent.com'),
('MS Virtual Assistant', 'global-va', 0, 1, 1, 0, 'msvirtualassistant.com.au'),
('Magic (GetMagic)', 'global-va', 0, 1, 1, 0, 'https://getmagic.com'),
('Magic Virtual Assistant Services', 'global-va', 0, 1, 1, 0, 'https://getmagic.pinpointhq.com'),
('Manpower Genius', 'global-va', 0, 1, 1, 0, 'https://manpowergenius.com/guide-for-uk-businesses/unlocking-efficiency-and-talent-outsourcing-your-office-staff-to-the-philippines-with-manpower-genius/'),
('MultiplyMii', 'global-va', 0, 1, 1, 0, 'https://www.multiplymii.com/'),
('My Cloud Assistant', 'global-va', 0, 1, 1, 0, 'https://www.mycloudassistant.com.au/'),
('My Freight Staff', 'global-va', 0, 1, 1, 0, 'https://myfreightstaff.ph/'),
('My Virtudesk', 'global-va', 0, 1, 1, 0, 'https://myvirtudesk.com/'),
('MyOutDesk', 'global-va', 0, 1, 1, 0, 'https://www.myoutdesk.com/'),
('OVA Virtual', 'global-va', 0, 1, 1, 0, 'https://ovavirtual.com'),
('OVA Virtual Assistant', 'global-va', 0, 1, 1, 0, 'https://ovavirtual.com/'),
('Officium', 'global-va', 0, 1, 1, 0, 'https://officium.ph'),
('Olivia Pros', 'global-va', 0, 1, 1, 0, 'https://www.oliviapros.com/careers'),
('OneVirtual Global Business Solutions', 'global-va', 0, 1, 1, 0, 'https://onevirtualsolutions.com'),
('OnlineHelpers', 'global-va', 0, 1, 1, 0, 'https://onlinehelpers.info/'),
('OnlineJobs', 'global-va', 0, 1, 1, 0, 'https://www.onlinejobs.ph/'),
('Outshore', 'global-va', 0, 1, 1, 0, 'https://outshore.com.au/'),
('Outsource Accelerator', 'global-va', 0, 1, 1, 0, 'https://outsourceaccelerator.com'),
('Outsource Access', 'global-va', 0, 1, 1, 0, 'https://outsourceaccess.com'),
('Outsource Philippines', 'global-va', 0, 1, 1, 0, 'https://www.outsourcephilippines.com'),
('Outsource Workers', 'global-va', 0, 1, 1, 0, 'https://outsourceworkers.com.au/'),
('Outsourced.ph', 'global-va', 0, 1, 1, 0, 'https://outsourced.ph'),
('Outsourcey', 'global-va', 0, 1, 1, 0, 'https://outsourcey.com/'),
('Outsourcing Angel', 'global-va', 0, 1, 1, 0, 'https://outsourcingangel.com'),
('PMVA (Property Management Virtual Assistant)', 'global-va', 0, 1, 1, 0, 'pmva.com.au'),
('Pearl Talent', 'global-va', 0, 1, 1, 0, 'https://www.pearltalent.com'),
('Pen Brothers', 'global-va', 0, 1, 1, 0, 'https://penbrothers.com'),
('Pepper Virtual Assistants', 'global-va', 0, 1, 1, 0, 'https://peppervirtualassistant.com/'),
('Philippines Recruitment UK', 'global-va', 0, 1, 1, 0, 'https://philippinesrecruitment.co.uk/'),
('Pineapple Staffing', 'global-va', 0, 1, 1, 0, 'https://pineapplestaffing.com/'),
('Platinum Outsourcing', 'global-va', 0, 1, 1, 0, 'https://platinumoutsourcing.com.au/'),
('Prialto', 'global-va', 0, 1, 1, 0, 'https://www.prialto.com'),
('ProSource', 'global-va', 0, 1, 1, 0, 'https://prosource.com.au/'),
('PropVA', 'global-va', 0, 1, 1, 0, 'https://propva.co.uk');

INSERT INTO va_directory (company_name, niche, is_dayshift, is_verified, is_remote, is_marketplace, website) VALUES
('Prosper VA', 'global-va', 0, 1, 1, 0, 'https://prosperva.com'),
('Quantum Virtual Assistants', 'global-va', 0, 1, 1, 0, 'https://quantumvirtualassistant.com'),
('REassist', 'global-va', 0, 1, 1, 0, 'reassist.com.au'),
('Ramsay Health Care', 'global-va', 0, 1, 1, 0, 'https://ramsayhealth.com'),
('Remote CoWorker', 'global-va', 0, 1, 1, 0, 'https://remotecoworker.com'),
('Remote Raven', 'global-va', 0, 1, 1, 0, 'https://hireremoteraven.com'),
('Remote Staff (Australia)', 'global-va', 0, 1, 1, 0, 'https://www.remotestaff.com.au/'),
('Remote Staff Philippines', 'global-va', 0, 1, 1, 0, 'https://www.remotestaff.ph/'),
('Remote Workmate', 'global-va', 0, 1, 1, 0, 'https://remoteworkmate.com'),
('Rocket Station', 'global-va', 0, 1, 1, 0, 'https://rocketstation.com'),
('SOS VA Services / Smart Outsourcing Solution', 'global-va', 0, 1, 1, 0, 'https://smartoutsourcingsolution.com/virtual-assistant-services-philippines/'),
('Scale Virtually', 'global-va', 0, 1, 1, 0, 'https://scalevirtually.com'),
('Scotiabank Canada', 'global-va', 0, 1, 1, 0, 'https://scotiabank.com'),
('SharkHelpers', 'global-va', 0, 1, 1, 0, 'https://sharkhelpers.com'),
('Smart Outsourcing Solution (SOS)', 'global-va', 0, 1, 1, 0, 'https://smartoutsourcingsolution.com/'),
('Sourcefit', 'global-va', 0, 1, 1, 0, 'https://sourcefit.com'),
('Sphere Rocket', 'global-va', 0, 1, 1, 0, 'https://sphererocketva.com'),
('Staff Avenue', 'global-va', 0, 1, 1, 0, 'https://staffavenue.co.uk/hire-virtual-staff-in-philippines/'),
('Staff Domain', 'global-va', 0, 1, 1, 0, 'https://staffdomain.com'),
('StaffVirtual', 'global-va', 0, 1, 1, 0, 'https://www.staffvirtual.com'),
('Staffing.com', 'global-va', 0, 1, 1, 0, 'https://staffing.com'),
('StaffingSolutions.io', 'global-va', 0, 1, 1, 0, 'https://staffingsolutions.io'),
('StaffingSolutions.io (SSIO)', 'global-va', 0, 1, 1, 0, 'https://staffingsolutions.io/'),
('Stellar Staff', 'global-va', 0, 1, 1, 0, 'https://stellarstaff.com/'),
('SuperStaff', 'global-va', 0, 1, 1, 0, 'https://superstaff.com/'),
('Support Shepherd', 'global-va', 0, 1, 1, 0, 'https://www.somewhere.com/'),
('Surge Virtual Assistants', 'global-va', 0, 1, 1, 0, 'https://surgevirtualassistants.com'),
('Talent Gateway', 'global-va', 0, 1, 1, 0, 'https://talentgateway.com'),
('TaskBullet', 'global-va', 0, 1, 1, 0, 'https://www.taskbullet.com/'),
('The Property VA', 'global-va', 0, 1, 1, 0, 'thepropertyva.co.uk'),
('The VA Hub PH', 'global-va', 0, 1, 1, 0, 'https://thevahub.org'),
('UAssist.ME', 'global-va', 0, 1, 1, 0, 'https://uassist.me'),
('USource', 'global-va', 0, 1, 1, 0, 'https://usource.me/services/virtual-assistants/'),
('VA Masters', 'global-va', 0, 1, 1, 0, 'https://vamasters.com'),
('VA Platinum', 'global-va', 0, 1, 1, 0, 'https://vaplatinum.com.au'),
('VA Staffer', 'global-va', 0, 1, 1, 0, 'https://vastaffer.com'),
('VAA Philippines', 'global-va', 0, 1, 1, 0, 'https://www.vaaphilippines.com'),
('Value VA', 'global-va', 0, 1, 1, 0, 'https://value-va.com'),
('Vaxtra', 'global-va', 0, 1, 1, 0, 'vaxtra.com'),
('Virtalent UK', 'global-va', 0, 1, 1, 0, 'virtalent.com'),
('Virtual Assistant Talent', 'global-va', 0, 1, 1, 0, 'https://virtualassistanttalent.com'),
('Virtual Assistants Philippines', 'global-va', 0, 1, 1, 0, 'https://virtualassistantsphilippines.com'),
('Virtual Champions', 'global-va', 0, 1, 1, 0, 'https://virtualchampions.ph/'),
('Virtual Coworker', 'global-va', 0, 1, 1, 0, 'https://virtualcoworker.com.au/'),
('Virtual Done Well', 'global-va', 0, 1, 1, 0, 'https://virtualdonewell.com'),
('Virtual Elves', 'global-va', 0, 1, 1, 0, 'https://virtualelves.com.au/'),
('Virtual Staff 365', 'global-va', 0, 1, 1, 0, 'https://www.virtualstaff365.com.au/'),
('Virtual Staff Finder', 'global-va', 0, 1, 1, 0, 'https://www.virtualstafffinder.com/careers/'),
('VirtualHub PH', 'global-va', 0, 1, 1, 0, 'https://virtualhub.ph/'),
('VirtualStaff', 'global-va', 0, 1, 1, 0, 'https://www.virtualstaff.ph/'),
('VirtualStaff.ph', 'global-va', 0, 1, 1, 0, 'https://www.virtualstaff.ph/en-ph'),
('Virtudesk', 'global-va', 0, 1, 1, 0, 'https://virtudesk.com'),
('Wing Assistant', 'global-va', 0, 1, 1, 0, 'https://wingassistant.com'),
('WoodBows', 'global-va', 0, 1, 1, 0, 'https://www.woodbows.com'),
('WorkMate Pro', 'global-va', 0, 1, 1, 0, 'https://www.workmatepro.com/'),
('WorkspaceCo Outsourcing', 'global-va', 0, 1, 1, 0, 'https://workspacecooutsourcing.com/'),
('eVirtualAssistants', 'global-va', 0, 1, 1, 0, 'https://www.evirtualassistants.com'),
('iWork.ph', 'global-va', 0, 1, 1, 0, 'https://iwork.ph'),
('Amazon (Remote PH)', 'ecommerce', 0, 1, 1, 0, 'https://www.amazon.jobs'),
('ConnectUs Marketing Solutions', 'ecommerce', 0, 1, 1, 0, 'https://connectusmarketing.com'),
('ConnectUs Marketing Solutions Inc.', 'ecommerce', 0, 1, 1, 0, 'https://connectusmarketing.com'),
('SellerPrism', 'ecommerce', 0, 1, 1, 0, 'https://sellerprism.com'),
('SmartBuyGlasses', 'ecommerce', 0, 1, 1, 0, 'https://www.smartbuyglasses.com'),
('SmartBuyGlasses (Remote PH)', 'ecommerce', 0, 1, 1, 0, 'https://www.smartbuyglasses.com'),
('Surge Digital Agency', 'ecommerce', 0, 1, 1, 0, 'https://surgedigital.agency'),
('Centerstone', 'bpo', 0, 1, 1, 0, 'https://centerstone.org'),
('Cognizant', 'bpo', 0, 1, 1, 0, 'https://www.cognizant.com'),
('Concentrix', 'bpo', 0, 1, 1, 0, 'https://www.concentrix.com'),
('Foundever (formerly Sitel)', 'bpo', 0, 1, 1, 0, 'https://foundever.com'),
('Genpact', 'bpo', 0, 1, 1, 0, 'https://www.genpact.com'),
('Global Strategic', 'bpo', 0, 1, 1, 0, 'https://globalstrategic.com'),
('Majorel', 'bpo', 0, 1, 1, 0, 'https://www.majorel.com'),
('ModSquad', 'bpo', 0, 1, 1, 0, 'https://modsquad.com'),
('Staff Boom', 'bpo', 0, 1, 1, 0, 'https://staffboom.com'),
('Sutherland Global', 'bpo', 0, 1, 1, 0, 'https://www.sutherlandglobal.com'),
('TELUS International', 'bpo', 0, 1, 1, 0, 'https://www.telusinternational.com'),
('TTEC', 'bpo', 0, 1, 1, 0, 'https://www.ttec.com'),
('TaskUs', 'bpo', 0, 1, 1, 0, 'https://www.taskus.com'),
('Teleperformance', 'bpo', 0, 1, 1, 0, 'https://www.teleperformance.com'),
('Unity Communications', 'bpo', 0, 1, 1, 0, 'https://unity-communications.com'),
('VXI Global Solutions', 'bpo', 0, 1, 1, 0, 'https://vxi.com'),
('Accenture Philippines', 'tech', 0, 1, 1, 0, 'https://www.accenture.com/ph-en'),
('Appen', 'tech', 0, 1, 1, 0, 'https://appen.com'),
('Crisp', 'tech', 0, 1, 1, 0, 'https://www.crisp.chat'),
('Radix Systems Services', 'tech', 0, 1, 1, 0, 'https://radixsys.com'),
('Wipro', 'tech', 0, 1, 1, 0, 'https://www.wipro.com'),
('Jobrack', 'job-boards', 0, 1, 1, 0, 'https://jobrack.eu'),
('OnlineJobs.ph', 'job-boards', 0, 1, 1, 0, 'https://www.onlinejobs.ph'),
('Remote Jobs Philippines (Instagram)', 'job-boards', 0, 1, 1, 0, 'https://www.instagram.com/remotejobsph'),
('Remote Staff PH', 'job-boards', 0, 1, 1, 0, 'https://www.remotestaff.ph'),
('Remotive', 'job-boards', 0, 1, 1, 0, 'https://remotive.com'),
('The Work at Home Woman', 'job-boards', 0, 1, 1, 0, 'https://www.theworkathomewoman.com'),
('ThinkRemote.org', 'job-boards', 0, 1, 1, 0, 'https://thinkremote.org'),
('We Work Remotely', 'job-boards', 0, 1, 1, 0, 'https://weworkremotely.com'),
('Working Nomads', 'job-boards', 0, 1, 1, 0, 'https://www.workingnomads.com'),
('ConnectOS', 'australian-dayshift', 1, 1, 1, 0, 'https://connectos.co'),
('EMAPTA', 'australian-dayshift', 1, 1, 1, 0, 'https://emapta.com'),
('Hammerjack', 'australian-dayshift', 1, 1, 1, 0, 'https://hammerjack.com.au'),
('Knights of Online Sales (KOOS)', 'australian-dayshift', 1, 1, 1, 0, 'https://koos.com.au'),
('MicroSourcing', 'australian-dayshift', 1, 1, 1, 0, 'https://www.microsourcing.com');

INSERT INTO va_directory (company_name, niche, is_dayshift, is_verified, is_remote, is_marketplace, website) VALUES
('Remote Talent Australia', 'australian-dayshift', 1, 1, 1, 0, 'https://remotetalentaustralia.com'),
('Satellite Office', 'australian-dayshift', 1, 1, 1, 0, 'https://www.satelliteoffice.com.au'),
('The Remote Group', 'australian-dayshift', 1, 1, 1, 0, 'https://theremotegroup.com'),
('Virtual Assistant Academy (VAA)', 'australian-dayshift', 1, 1, 1, 0, 'https://www.vaa.ph'),
('Fiverr', 'global-va', 0, 1, 1, 1, 'https://www.fiverr.com');

