DELETE FROM va_directory;

INSERT INTO va_directory (company_name, niche, is_dayshift, is_verified, is_remote, is_marketplace, website) VALUES
('Affordable Staff', 'australian-dayshift', 1, 1, 1, 0, 'https://affordablestaff.com.au'),
('Diversify', 'australian-dayshift', 1, 1, 1, 0, 'https://diversify.com'),
('EzyVA', 'australian-dayshift', 1, 1, 1, 0, 'https://ezyva.com'),
('Hudson Remote', 'australian-dayshift', 1, 1, 1, 0, 'https://hudson.com'),
('Shore360', 'australian-dayshift', 1, 1, 1, 0, 'https://shore360.com.au'),
('Vyla', 'australian-dayshift', 1, 1, 1, 0, 'https://vyla.com.au'),
('Yacan!', 'australian-dayshift', 1, 1, 1, 0, 'https://yacan.com.au'),
('ConnectOS', 'australian-dayshift', 1, 1, 1, 0, 'https://connectos.co'),
('EMAPTA', 'australian-dayshift', 1, 1, 1, 0, 'https://emapta.com'),
('Hammerjack', 'australian-dayshift', 1, 1, 1, 0, 'https://hammerjack.com.au'),
('Knights of Online', 'australian-dayshift', 1, 1, 1, 0, 'https://knightsofonlinemarketers.com'),
('MicroSourcing', 'australian-dayshift', 1, 1, 1, 0, 'https://microsourcing.com'),
('Remote Talent', 'australian-dayshift', 1, 1, 1, 0, 'https://remotetalent.com.au'),
('Satellite Office', 'australian-dayshift', 1, 1, 1, 0, 'https://satelliteoffice.com'),
('The Remote Group', 'australian-dayshift', 1, 1, 1, 0, 'https://theremotegroup.com'),

('Upwork', 'global-va', 0, 0, 1, 1, 'https://upwork.com'),
('20Four7VA', 'global-va', 0, 1, 1, 0, 'https://20four7va.com'),
('24x7 Virtual Assistants', 'global-va', 0, 1, 1, 0, 'https://24x7virtualassistants.com'),
('24x7 Direct', 'global-va', 0, 1, 1, 0, 'https://24x7direct.com.au'),
('AUMTREND PH', 'global-va', 0, 1, 1, 0, 'https://aumtrend.com'),
('AUMTREND PHIL', 'global-va', 0, 1, 1, 0, 'https://aumtrend.com'),
('Access Offshoring', 'global-va', 0, 1, 1, 0, 'https://accessoffshoring.com.au'),
('AgentSync', 'global-va', 0, 1, 1, 0, 'https://agentsync.com.au'),
('Arms & Sourcing', 'global-va', 0, 1, 1, 0, 'https://armasourcing.com'),
('Athena Executive', 'global-va', 0, 1, 1, 0, 'https://athenaassistant.com'),
('Beepo', 'global-va', 0, 1, 1, 0, 'https://beepo.com.au'),
('Belay Solutions', 'global-va', 0, 1, 1, 0, 'https://belaysolutions.com'),
('Big Outsource', 'global-va', 0, 1, 1, 0, 'https://bigoutsource.com'),
('Boldly', 'global-va', 0, 1, 1, 0, 'https://boldly.com'),
('Booth & Partners', 'global-va', 0, 1, 1, 0, 'https://boothandpartners.com'),

('Centerstone', 'bpo', 0, 1, 1, 0, 'https://centerstone.com'),
('Cognizant', 'bpo', 0, 1, 1, 0, 'https://cognizant.com'),
('Concentrix', 'bpo', 0, 1, 1, 0, 'https://concentrix.com'),
('Foundever', 'bpo', 0, 1, 1, 0, 'https://foundever.com'),
('Genpact', 'bpo', 0, 1, 1, 0, 'https://genpact.com'),
('Global Strategic', 'bpo', 0, 1, 1, 0, 'https://globalstrategic.com'),
('Majorel', 'bpo', 0, 1, 1, 0, 'https://majorel.com'),
('ModSquad', 'bpo', 0, 1, 1, 0, 'https://modsquad.com'),
('Staff Boom', 'bpo', 0, 1, 1, 0, 'https://staffboom.com'),
('Sutherland Global', 'bpo', 0, 1, 1, 0, 'https://sutherlandglobal.com'),
('TELUS International', 'bpo', 0, 1, 1, 0, 'https://telusinternational.com'),
('TTEC', 'bpo', 0, 1, 1, 0, 'https://ttec.com'),
('TaskUs', 'bpo', 0, 1, 1, 0, 'https://taskus.com'),
('Teleperformance', 'bpo', 0, 1, 1, 0, 'https://teleperformance.com'),
('Unity', 'bpo', 0, 1, 1, 0, 'https://unity.com'),

('Jobrack', 'job-boards', 0, 1, 1, 0, 'https://jobrack.eu'),
('OnlineJobs.ph', 'job-boards', 0, 1, 1, 0, 'https://onlinejobs.ph'),
('Remote Staff PH', 'job-boards', 0, 1, 1, 0, 'https://remotestaff.ph'),
('Remotiko', 'job-boards', 0, 1, 1, 0, 'https://remotiko.com'),
('The Work at Home', 'job-boards', 0, 1, 1, 0, 'https://theworkathome.com'),
('ThinkRemote', 'job-boards', 0, 1, 1, 0, 'https://thinkremote.com'),
('We Work Remotely', 'job-boards', 0, 1, 1, 0, 'https://weworkremotely.com'),
('Working Nomads', 'job-boards', 0, 1, 1, 0, 'https://workingnomads.com'),

('Amazon', 'ecommerce', 0, 1, 1, 0, 'https://amazon.jobs'),
('ConnectUs', 'ecommerce', 0, 1, 1, 0, 'https://connectus.com'),
('SellerPrism', 'ecommerce', 0, 1, 1, 0, 'https://sellerprism.com'),
('SmartBuyGlasses', 'ecommerce', 0, 1, 1, 0, 'https://smartbuyglasses.com'),
('Surge Digital', 'ecommerce', 0, 1, 1, 0, 'https://surgedigital.agency'),

('Accenture', 'tech', 0, 1, 1, 0, 'https://accenture.com'),
('Appen', 'tech', 0, 1, 1, 0, 'https://appen.com'),
('Crisp', 'tech', 0, 1, 1, 0, 'https://crisp.chat'),
('Radix', 'tech', 0, 1, 1, 0, 'https://radix.com'),
('Wipro', 'tech', 0, 1, 1, 0, 'https://wipro.com');
