import { describe, it, expect } from "bun:test";
import {
  buildPermissionEvidencePack,
  attachPermissionToSourceAccount,
  renderPermissionPackReport,
  PERMISSION_LEASE_DAYS,
  type PermissionEvidencePackInput,
} from "./partner-permission";

// Real, revalidated facts (fetched 2026-08-29) — not invented. Each target's
// null fields reflect genuinely undocumented mechanisms, not omissions.

const ASHBY_INPUT: PermissionEvidencePackInput = {
  targetProvider: "ashby",
  displayName: "Ashby (dedicated partner job feed)",
  providerRoute: "https://developers.ashbyhq.com/docs/dedicated-partner-job-feeds",
  contactPath: "integrations@ashbyhq.com",
  requestedScope: "Read-only dedicated partner job feed (JSON/XML) for customers who explicitly enable our integration in Ashby's Admin section",
  dataMinimization: "Store only minimal factual metadata (title, company, location, work type, canonical apply link); full descriptions only if explicitly permitted",
  attribution: "Canonical linkback to the original Ashby job posting URL on every listing",
  cadence: "Hourly (matches Ashby's documented feed update cadence)",
  removalSemantics: "Deactivate within one successful reconciliation cycle after a posting disappears from a complete feed pull",
  noCandidateDataTerms: "We do not collect, store, or process candidate/applicant data of any kind — only public job posting metadata",
  evidenceUrl: "https://developers.ashbyhq.com/docs/dedicated-partner-job-feeds",
  notes: "Ashby's documentation specifies no attribution/usage-restriction terms for the partner feed; the request to integrations@ashbyhq.com should explicitly confirm attribution and content-scope expectations before any customer is asked to enable the integration. Customers must individually opt in via Ashby's Admin section — this is a customer-authorized mechanism even though the technical route is a Ashby-operated partner feed.",
};

// Breezy documents NO third-party partner-request path at all: API access is
// a Personal Access Token generated by the CUSTOMER (the employer) inside
// their own Breezy account. providerRoute/contactPath are honestly null.
const BREEZY_INPUT: PermissionEvidencePackInput = {
  targetProvider: "breezy",
  displayName: "Breezy HR (employer-authorized Positions API)",
  providerRoute: null,
  contactPath: null,
  requestedScope: "Not applicable via a Breezy-level partner path — access requires an already-directory-listed employer using Breezy to generate and share their own Personal Access Token (PAT) from their account's API Keys settings",
  dataMinimization: "Minimal facts only, same as every other public-index source",
  attribution: "Canonical linkback to the employer's own Breezy posting URL",
  cadence: "Employer-specific, respecting Breezy's own (undocumented) API rate limits",
  removalSemantics: "Deactivate within one successful reconciliation cycle; stop immediately if the employer revokes the PAT",
  noCandidateDataTerms: "We do not collect, store, or process candidate/applicant data",
  evidenceUrl: "https://developer.breezy.hr/reference/authorization",
  notes: "Breezy has no documented partner/integration program to request access from Breezy itself — every API request (except /v3/signin and /v3/health) requires a PAT the CUSTOMER creates in their own account. The only compliant acquisition path is employer opt-in (matching this project's existing 'permissioned' tier), not partner outreach to Breezy. The generic career-site /json route used historically is explicitly not the perpetual path (strategy doc). No generic Breezy source is activated by this evidence pack.",
};

const JOBVITE_INPUT: PermissionEvidencePackInput = {
  targetProvider: "jobvite",
  displayName: "Jobvite (partner marketplace)",
  providerRoute: "https://www.jobvite.com/marketplace/partner-request/",
  contactPath: "Partner application: https://www.jobvite.com/marketplace/partner-request/ ; demo request: https://www.jobvite.com/lp/request-a-demo/ ; phone (888) 885-5299",
  requestedScope: "Partner/marketplace integration access for read-only job-posting syndication (exact API scope not publicly documented — to be confirmed during partner application)",
  dataMinimization: "Minimal facts only",
  attribution: "Canonical linkback to the original Jobvite posting",
  cadence: "To be confirmed with Jobvite during partner onboarding — no public rate guidance found",
  removalSemantics: "Deactivate within one successful reconciliation cycle",
  noCandidateDataTerms: "We do not collect, store, or process candidate/applicant data",
  evidenceUrl: "https://www.jobvite.com/partners/",
  notes: "No developer/API documentation URL was found on Jobvite's public partner marketplace page; the partner application process itself will presumably surface the actual technical/legal terms. This pack is outreach-ready in the sense that a partner-application path exists to submit our request — the partner's own terms remain genuinely unknown until Jobvite responds. No generic Jobvite source is activated by this evidence pack.",
};

describe("partner-permission — evidence pack builder (SP-17 criterion 1: every required field present or explicitly missing)", () => {
  it("Ashby: every field documented -> outreach_ready", () => {
    const pack = buildPermissionEvidencePack(ASHBY_INPUT, "2026-08-29T14:00:00.000Z");
    expect(pack.status).toBe("outreach_ready");
    expect(pack.missingFields).toEqual([]);
    expect(pack.providerRoute).toContain("ashbyhq.com");
    expect(pack.contactPath).toBe("integrations@ashbyhq.com");
  });

  it("Breezy: no partner path documented -> draft, missing providerRoute and contactPath", () => {
    const pack = buildPermissionEvidencePack(BREEZY_INPUT, "2026-08-29T14:00:00.000Z");
    expect(pack.status).toBe("draft");
    expect(pack.missingFields).toContain("providerRoute");
    expect(pack.missingFields).toContain("contactPath");
    expect(pack.missingFields).not.toContain("dataMinimization");
    expect(pack.missingFields).not.toContain("noCandidateDataTerms");
  });

  it("Jobvite: partner application path documented -> outreach_ready", () => {
    const pack = buildPermissionEvidencePack(JOBVITE_INPUT, "2026-08-29T14:00:00.000Z");
    expect(pack.status).toBe("outreach_ready");
    expect(pack.missingFields).toEqual([]);
    expect(pack.providerRoute).toContain("jobvite.com");
  });

  it("a pack missing every field is draft with all nine fields listed as missing", () => {
    const empty: PermissionEvidencePackInput = {
      targetProvider: "unknown", displayName: "Unknown target",
      providerRoute: null, contactPath: null, requestedScope: null,
      dataMinimization: null, attribution: null, cadence: null,
      removalSemantics: null, noCandidateDataTerms: null, evidenceUrl: null,
    };
    const pack = buildPermissionEvidencePack(empty, "2026-08-29T14:00:00.000Z");
    expect(pack.status).toBe("draft");
    expect(pack.missingFields).toHaveLength(9);
  });

  it("is pure — identical input yields identical output", () => {
    const a = buildPermissionEvidencePack(ASHBY_INPUT, "2026-08-29T14:00:00.000Z");
    const b = buildPermissionEvidencePack(ASHBY_INPUT, "2026-08-29T14:00:00.000Z");
    expect(a).toEqual(b);
  });
});

describe("partner-permission — lease and attach (SP-17 criterion 2: 365-day lease, revocation handling)", () => {
  it("attachPermissionToSourceAccount computes a 365-day policyExpiry from the grant instant", () => {
    const attached = attachPermissionToSourceAccount("ashby:granted-partner", "ashby", "2026-08-29T00:00:00.000Z");
    expect(PERMISSION_LEASE_DAYS).toBe(365);
    expect(attached.policyExpiry).toBe("2027-08-29T00:00:00.000Z");
    expect(attached.revocationMechanism).toBe("source_opt_outs");
    expect(attached.sourceId).toBe("ashby:granted-partner");
  });

  it("supports a custom lease length", () => {
    const attached = attachPermissionToSourceAccount("x", "y", "2026-01-01T00:00:00.000Z", 30);
    expect(attached.policyExpiry).toBe("2026-01-31T00:00:00.000Z");
  });

  it("revocation reuses SP-05's existing mechanism — no new revocation type is invented", () => {
    const attached = attachPermissionToSourceAccount("breezy:acme", "breezy", "2026-08-29T00:00:00.000Z");
    expect(attached.revocationMechanism).toBe("source_opt_outs");
  });
});

describe("partner-permission — no generic source activated (SP-17 criterion 3)", () => {
  it("building or attaching a pack performs no D1 write and returns plain data only", () => {
    const pack = buildPermissionEvidencePack(ASHBY_INPUT, "2026-08-29T14:00:00.000Z");
    const attached = attachPermissionToSourceAccount("ashby:acme", "ashby", "2026-08-29T14:00:00.000Z");
    // Both are plain serializable objects — proof there is no side effect,
    // network call, or hidden activation path in this module.
    expect(JSON.parse(JSON.stringify(pack))).toEqual(pack);
    expect(JSON.parse(JSON.stringify(attached))).toEqual(attached);
  });
});

describe("partner-permission — report generation", () => {
  it("report includes every field, status, and the lease/revocation explanation", () => {
    const pack = buildPermissionEvidencePack(ASHBY_INPUT, "2026-08-29T14:00:00.000Z");
    const report = renderPermissionPackReport(pack);
    expect(report).toContain("Ashby (dedicated partner job feed)");
    expect(report).toContain("outreach_ready");
    expect(report).toContain("integrations@ashbyhq.com");
    expect(report).toContain("365-day");
    expect(report).toContain("source_opt_outs");
    expect(report).toContain("No message has been sent and no source has been activated");
  });

  it("a draft pack's report lists exactly which fields are missing", () => {
    const pack = buildPermissionEvidencePack(BREEZY_INPUT, "2026-08-29T14:00:00.000Z");
    const report = renderPermissionPackReport(pack);
    expect(report).toContain("draft");
    expect(report).toContain("## Missing");
    expect(report).toContain("`providerRoute`");
    expect(report).toContain("`contactPath`");
  });
});
