steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--progress=plain'
      - '-t'
      - '$_IMAGE_TAG'
      - '-f'
      - 'infra/gcp/lake-publish/Dockerfile'
      - '.'
images:
  - '$_IMAGE_TAG'
substitutions:
  _IMAGE_TAG: ''
